version: '3.1'
services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: aie
      MYSQL_ROOT_PASSWORD: aie
      MYSQL_USER: aie
      MYSQL_PASSWORD: aie
  kurento:
    image: kurento/kurento-media-server:latest
    container_name: kurento_media_server
    ports:
      - "8888:8888"
    environment:
      - KMS_MIN_PORT=20000
      - KMS_MAX_PORT=30000
      - GST_DEBUG=Kurento*:5  # 디버그 레벨 설정
    volumes:
      - ./video/:/var/lib/kurento/